<h2>Unexpected error happenend</h3>
<p> This is the rescue page. See the exception details below </p>
<pre>
${context.LastException.GetType().Name}

Message:
  ${context.LastException.Message}
  
StackTrace:
  ${context.LastException.StackTrace}
  
InnerException:
  $!{context.LastException.InnerException}

</pre>